:accounts:
  :access_key_id: AAAAAAAAAAAAAAAAAA
  :secret_access_key: BBBBBBBBBBBBBBBBBBBBBBBB

:regions:
  - us-east-1
  - us-west-2
  - us-west-1
  - eu-west-1
  - eu-central-1
  - ap-southeast-1
  - ap-southeast-2
  - ap-northeast-1
  - sa-east-1
   
